### PR TITLE
Branching JP Papa Smurf table commit

### PR DESCRIPTION
**Pull request by T3chZombie**

### CODE REVIEW

**Comment by T3chZombie** [comment]
I thought that file was automatically generated for the high scores? Seems silly that we have to keep adding that to every table when it could be automated. The video that was posted only showed how to add the branch with a vpin table and never showed that we needed to included the  readme for the main index. Did I watch the wrong video?

**Comment by SScorpio00** [comment]
You did everything right in terms of the branch, but in the table readme you are referencing vpx-bravestar.

To fix that open GitHub Desktop and use the dropdown to select the branch. Then edit the file, and commit it. You do **NOT** need to create another pull request. The Readme update will automatically get attached to this one.

**Comment by SScorpio00** [comment]
> Also, do not forget to add the pull request to insert the game into the main index.
> 
> To do this, here are a couple of screenshots as an example...
> 
> You do this on your OWN fork of the main. Not on the main.

That was already done. If you clicked the Files Changed tab it will show everything that's modified. Just look for the root README.md in there.

**Comment by T3chZombie** [comment]
Ok. Thanks for all the help. Appreciate it. Hopefully the next table(s) I start submitting will be better. No promises there won't be a mistake, but I'll do my best to try and not have any.

**Pull request merged**
